// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multitenant.Data;

#nullable disable

namespace Multitenant.Migrations
{
    [DbContext(typeof(MultitenantDbContext))]
    partial class MultitenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Multitenant.Models.Chat", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FileUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ChatId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Multitenant.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Multitenant.Models.PostMessage", b =>
                {
                    b.Property<string>("PostMessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FileUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PostMessageId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("PostMessages");
                });

            modelBuilder.Entity("Multitenant.Models.RegistrationRequest", b =>
                {
                    b.Property<string>("RegistrationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignedManagerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NotificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RegistrationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("Multitenant.Models.ResponseMessage", b =>
                {
                    b.Property<string>("ResponseMessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("FileUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NotificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostMessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RepliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ResponseMessageId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("PostMessageId");

                    b.HasIndex("UserId");

                    b.ToTable("ResponseMessages");
                });

            modelBuilder.Entity("Multitenant.Models.Tenant", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Multitenant.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RegistrationRequestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RegistrationRequestId")
                        .IsUnique()
                        .HasFilter("[RegistrationRequestId] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "A001",
                            CreatedAt = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Admin",
                            Email = "prathyushareddy3112@gmail.com",
                            Password = "prathyusha@123",
                            Role = 0,
                            UserName = "Prathyusha"
                        });
                });

            modelBuilder.Entity("Multitenant.Models.Chat", b =>
                {
                    b.HasOne("Multitenant.Models.User", "ReceiverUser")
                        .WithMany("ReceivedChats")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multitenant.Models.User", "SenderUser")
                        .WithMany("SentChats")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Multitenant.Models.Notification", b =>
                {
                    b.HasOne("Multitenant.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Multitenant.Models.PostMessage", b =>
                {
                    b.HasOne("Multitenant.Models.Tenant", "Tenant")
                        .WithMany("PostMessages")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multitenant.Models.User", "User")
                        .WithMany("PostMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Multitenant.Models.RegistrationRequest", b =>
                {
                    b.HasOne("Multitenant.Models.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Multitenant.Models.ResponseMessage", b =>
                {
                    b.HasOne("Multitenant.Models.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId");

                    b.HasOne("Multitenant.Models.PostMessage", "PostMessage")
                        .WithMany("ResponseMessages")
                        .HasForeignKey("PostMessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Multitenant.Models.User", "User")
                        .WithMany("ResponseMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("PostMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Multitenant.Models.User", b =>
                {
                    b.HasOne("Multitenant.Models.RegistrationRequest", "RegistrationRequest")
                        .WithOne("ApprovedUser")
                        .HasForeignKey("Multitenant.Models.User", "RegistrationRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Multitenant.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RegistrationRequest");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Multitenant.Models.PostMessage", b =>
                {
                    b.Navigation("ResponseMessages");
                });

            modelBuilder.Entity("Multitenant.Models.RegistrationRequest", b =>
                {
                    b.Navigation("ApprovedUser");
                });

            modelBuilder.Entity("Multitenant.Models.Tenant", b =>
                {
                    b.Navigation("PostMessages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Multitenant.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("PostMessages");

                    b.Navigation("ReceivedChats");

                    b.Navigation("ResponseMessages");

                    b.Navigation("SentChats");
                });
#pragma warning restore 612, 618
        }
    }
}
